### ISSUE TITLE
External

### ISSUE THREAD

**Issue by fuckusfm** [SpoilerRules/server-list-explorer#2]
Add an option to be in another window 
OR
Add an option to be a driver so that everytime you boot up a little icon tray will pop up
When you open it. a new window will pop up for you to select a server
If a server was selected to connect minecraft will launch and connect to that server

good luck making that nub

**Comment by SpoilerRules** [comment]
The first suggestion, "add an option to be in another window," isn’t entirely clear. 

The second idea falls outside the intended scope of the project. This software is built to be lightweight and straightforward, not a persistent background service.

As for the third suggestion, automating Minecraft launch and server connections doesn’t align with the tool’s purpose. This project focuses on helping you explore and manage your server list, not on functioning as a Minecraft launcher.

I appreciate your suggestions, but they don’t align with the current vision for this project.
